[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[terminal.shell]
program = "zsh"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.6
blur = true

padding.x = 1
padding.y = 3

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium"}
bold = { family = "JetBrains Mono Nerd Font", style = "Bold"}
italic = { family = "JetBrains Mono Nerd Font", style = "MediumItalic"}
bold_italic = { family = "JetBrains Mono Nerd Font", style = "BoldItalic"}

size = 13.0

[keyboard]
bindings = [
  { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "_", mods = "Control|SHift", action = "DecreaseFontSize" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  # Envia Ctrl+= e Ctrl+- como caracteres de controle
  { key = "=", mods = "Control", chars = "\u001d"},
  { key = "-", mods = "Control", chars = "\u001f"},
]
